### ISSUE TITLE
How can I configure it on Icinga?

### ISSUE THREAD

**Issue by duven87** [aheissenberger/nagios-check_curl#1]
Hello!
I just discovered this check that works very well for some web pages that http_check cannot.

My problem is that I still don't know how to integrate it in Icinga.

Can someone help me to configure it as a service and then give it different variables and strings to search?

Thanks

Regards!

**Comment by aheissenberger** [comment]
What you need to do is to create a command which maps the parameters in a service to the plugin:
https://www.howtoforge.com/tutorial/write-a-custom-nagios-check-plugin/

**Comment by duven87** [comment]
SOLVED:

command:

```
command = [ PluginDir + "/check_curl2" ]
arguments += {
"-U" = "$curl_url$"
"-F" = {
set_if = "$follow$"
required = false
}
"-G" = "$curl_string$"
}
}
```

service: curl-services.conf:

```
apply Service "curl_pattern-" for (website_curl => config in host.vars.website_curl) {
import "generic-service"
check_command = "check-curl2"
vars += config

}
```

and in a Host config file:

```
vars.website_curl["example.com"] = {
curl_url = "https://example.com/typo3/index.php"
curl_follow = "true"
curl_string = "findme"
}
```

**Comment by aheissenberger** [comment]
oh - this looks different than I am used to do it in nagios which I still use :-)
